### ISSUE TITLE
Format Dashboard.php file

### ISSUE THREAD

**Issue by GianlucaScarciolla** [MCHDStudio/Duolex#6]
@fuerbringer Could you format the file?

Thanks.

**Comment by fuerbringer** [comment]
I will do that once you execute querys in a for loop instead of copy pasting them.

**Comment by GianlucaScarciolla** [comment]
Oh, alright \* _work in progress_ *

**Comment by GianlucaScarciolla** [comment]
- [x] Added the for-loop
